#pragma once

#include <assets/kasset_types.h>

#include "kresources/kresource_types.h"

kresource_material_type kasset_material_type_to_kresource(kasset_material_type type);
kasset_material_type kresource_material_type_to_kasset(kresource_material_type type);

kresource_material_model kasset_material_model_to_kresource(kasset_material_model model);
kasset_material_model kresource_material_model_to_kasset(kresource_material_model model);

kresource_material_texture_map_channel kasset_material_tex_map_channel_to_kresource(kasset_material_texture_map_channel channel);
kasset_material_texture_map_channel kresource_material_tex_map_channel_to_kasset(kresource_material_texture_map_channel channel);

kresource_material_texture kasset_material_texture_to_kresource(kasset_material_texture texture);
kasset_material_texture kresource_material_texture_to_kasset(kresource_material_texture texture);

kresource_material_sampler kasset_material_sampler_to_kresource(kasset_material_sampler sampler);
kasset_material_sampler kresource_material_sampler_to_kasset(kresource_material_sampler sampler);
